version: "3.7"
services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  # application service
  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  # database service
  mongo_db:
      image: mongo:4.4
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - custom
networks:
  custom:
    driver: bridge